### ISSUE TITLE
To use `gpt-4-vision-preview` add an OpenAI API key?

### ISSUE THREAD

**Issue by LeDeliJelly** [OthersideAI/self-operating-computer#127]
sorry im new to this, but can someone help me with this issue? also does gpt 4 vision cost money?

**Comment by LeDeliJelly** [comment]
![image](https://github.com/OthersideAI/self-operating-computer/assets/92609665/ee7935aa-32fb-43e3-a00d-9e8b24d10178)

**Comment by GangstersPairOfDice** [comment]
The repo's [Quick Start Guide](https://github.com/OthersideAI/self-operating-computer#quick-start-instructions) should help you with this. You have to edit the .env file, and place your OpenAI API key where it says "api-key here" or like whatever.

Also, yes it does cost money, as you need access to GPT4, which requires a monthly subscription of 20usd per month.

An alternative is using Ollama's LLAVA model, you can access it using [this pull request](https://github.com/OthersideAI/self-operating-computer/pull/113). Requires Ollama, around 5gb of free space, and a somewhat good computer. You will also need to change the code if you are local hosting it. Sadly, lacks sufficient usage documentation. Oh well ;p

**Comment by joshbickett** [comment]
@GangstersPairOfDice's input is correct. On a related note, I improved the initial setup flow. Now all you need to do is do `pip install self-operating-computer` and then `operate`. It will prompt you for your openai key which makes the process smoother. I'll close this ticket for now since it is not bug related. Reopen a ticket if you have issues or other questions. Thanks
