### ISSUE TITLE
Click always off

### ISSUE THREAD

**Issue by DavidKotyk** [OthersideAI/self-operating-computer#22]
Can a coordinate grid be added to every screenshot so the clicks are not so off?

**Comment by rohanarun** [comment]
It's because they hard-positions in the prompt. This appears to be copying our multi-modal Atlas-1 model we trained to find all the UI-elements for you, so our model doesn't need to hard-code positions like this. 
![image](https://github.com/OthersideAI/self-operating-computer/assets/11659839/2dea99c3-b174-4894-9634-f9508098ec23)

Check out Atlas-1 searching google here, and it scans all the possible UI elements based on the probability to find the next click: https://youtu.be/IQuBA7MvUas We're releasing Atlas-1 in the coming week, but it took months to train to get to work on arbitrary automations and clicks. This design of hard-coded positions can't scale to all automations easily.

**Comment by DavidKotyk** [comment]
But the different screen resolutions can be scaled in code by pulling the resolution. I feel like not allowing the bot to truly click will limit the projects that can be done in the future. 

Like using Xcode or some other developer application will need precise clicks

**Comment by DavidKotyk** [comment]
I feel like if we keep requesting gpt 4 vision to have this ability, OpenAI will train it too. 

Thanks for the information and insight!
