### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by kannanspeed** [OthersideAI/self-operating-computer#46]
![Screenshot (187)](https://github.com/OthersideAI/self-operating-computer/assets/47640609/35d72ccf-4619-4bbf-9c2f-1f7fe2a1b93b)
If any new open ai API use is getting issues, don't worry. there is some issue from open ai side

**Comment by rftheisen** [comment]
I am having this same issue. The error I am getting is in the attached screenshot.
![image](https://github.com/OthersideAI/self-operating-computer/assets/52935050/c80d6f00-65b4-401b-b9fe-12fd681de89c)

**Comment by kannanspeed** [comment]
I too have the same problem

**Comment by rftheisen** [comment]
It may be a rate limiting issue because I just noticed when I went and clicked on the Usage details in the OpenAI API web UI a red window with an error message stating something to the effect of "Your are limited to 5 requests per minute, slow down". The weird thing is when I look at the other usage statistics its not showing that there have been any API requests at all. It feels like its on OpenAI's side.

**Comment by michaelhhogue** [comment]
Are you both still having this issue? @kannanspeed @rftheisen

**Comment by michaelhhogue** [comment]
This issue appears to be from OpenAI's side. Going ahead and closing this.

**Comment by michaelhhogue** [comment]
@JcrypticD Have you spent at least $5 in OpenAI API credits?

**Comment by JcrypticD** [comment]
Definitely have spent more than 5. Probably should have led with that. I mean you aren't able to help I'll be left with .copying and pasting the details to every llm aka all of them till somebody has the right answer, Chat's got me going in circles 
![api usage](https://github.com/OthersideAI/self-operating-computer/assets/139065955/66beb53c-f5b5-49cf-b3d2-ed7d79a8b684)

**Comment by JcrypticD** [comment]
Yes definitely spent more than 5. Probably should have led with that. If that was the solution previously, unfortunately it won't be the solution in this case.  Burn any help you can give me would be appreciated. Otherwise you'll find me shopping it to every LM in existence and to let somebody gives me the right answer. LOL.
![api usage](https://github.com/OthersideAI/self-operating-computer/assets/139065955/f3c705d8-f562-4aaf-8dac-fa6a39dead05)

**Comment by JcrypticD** [comment]
Upon further digging checking I put a call to the api directly through cmd and got back 

"object": "list",
  "data": [
    {
      "id": "text-search-babbage-doc-001",
      "object": "model",
      "created":
      "owned_by": "openai-dev"
    },
    {
      "id": "curie-search-query",
      "object": "model",
      "created": 
      "owned_by": "openai-dev"
    },
    {
      "id": "text-davinci-003",
      "object": "model",
      "created": 
      "owned_by": "openai-internal"
    },
    {
