### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by alafortu** [OthersideAI/self-operating-computer#66]
I played with gpt4V on other projects and it definitely has a hard time figuring out coordinates. I used other model trained on image identification to find the coordinates of the box made around the object detected and then I can pass it to gpt 4 to perform an action. For your use case, I juste tested this model "https://huggingface.co/foduucom/web-form-ui-field-detection" Far from being perfect, but maybe an idea to build on. If you auto computer can detect and get the proper coordinates of the input fields in an image, it could help or at least add a level of redundancy to improve accuracy in clicking and inputing stuff at the right places.

**Comment by rohanarun** [comment]
Warning: this project appears to have blatantly ripped off the work of researchers over a year on a new multi-modal model, Atlas-1, and is attempting to scam open source devs into doing that work #67
https://github.com/OthersideAI/self-operating-computer/issues/67#event-11129657365

**Comment by Bunger-Beesechurger** [comment]
@rohanarun
I'm not a contributor to this github, just part of the audience usually, but this seems earlier than your thing. Early August is when this article came out, so it's been in the works even earlier than that. Stop spamming every issue

![Screenshot (813)](https://github.com/OthersideAI/self-operating-computer/assets/124498059/646755a3-0a89-4a33-8542-b8b635c6598b)

**Comment by rohanarun** [comment]
> @rohanarun I'm not a contributor to this github, just part of the audience usually, but this seems earlier than your video. Early August is when this article came out, so it's been in the works even earlier than that. Stop spamming every issue. You said you've been working on your thing for over a year, but how much of the info came out before your video? I don't know whether it's plagiarizing or not, and if it is, I'm sorry. However, I can still be annoyed that on what should be a cool new project for tech advancement, we have to figure out if something is stealing or not.
> 
> ![Screenshot (813)](https://private-user-images.githubusercontent.com/124498059/287474895-646755a3-0a89-4a33-8542-b8b635c6598b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NTE5MjQsIm5iZiI6MTcwMTU1MTYyNCwicGF0aCI6Ii8xMjQ0OTgwNTkvMjg3NDc0ODk1LTY0Njc1NWEzLTBhODktNGEzMy04NTQyLWI4YjYzNWM2NTk4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQyMTEzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjcyZDRjMjE5YzQ0M2IyNDY5NGRkM2ZkODAyOWIyYjg5ZjVlYTVhZDg2NWUxNjkwMTIwNWRiZTgzODlmNzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WHixWDjdhCvoD-F1khDkIOTigwzMmUIwdmVM8GhKygo)
> 
> Article says "HyperWriteAI" and from this github's own main page: "Ongoing Development At HyperwriteAI, we are developing Agent-1-Vision a multimodal model with more accurate click location predictions" so it is referencing this project.

Our project was started in July 2022 before the chatGPT API was released, including public publications which we freely gave out and we intend to open source. What's concerning is they continue to steal the work without attribution. It took a year to train our new multi-modal model, and we've been working on agents since this post in July We've been working on this for over a year and we called them out on copying our launch in April as well, and our community has been aware of atlas-1: https://www.producthunt.com/products/cheat-layer#project-atlas-agents
https://www.producthunt.com/products/cheat-layer?utm_source=badge-top-post-badge&utm_medium=badge#cheat-layer

Never heard from the owners after multiple attempts, and it's pretty blatant now so we're going to warn open source developers. If they steal our work before we even open source it, they are a well funded scam that is taking advantage of open source developers. 

![image](https://github.com/OthersideAI/self-operating-computer/assets/11659839/661e4f4b-a61f-4b52-a4a8-c6c961d1d860)

**Comment by Kreijstal** [comment]
I mean you are saying you have a custom model, but all I see it's propietary and business products, your custom model is handwritten for the cases, but this is gpt-4V so it's not a rip off, they just had the idea (wouldn't it be cool if gpt-4 could control computers) and open sourced it first 🤷. It can't be a rip off because you started without gpt-4v, you trained a propietary custom model, these guys just did prompt engineering and got it wit gpt-4v to work, without taking any custom models. 

If these guys get more fame it's because they open sourced it first, and then it's first come first serve. I think it's fair. imho.

Also your insecurity is showing, if your product was really good there is no need to spam it on every issue. Just give us something better and people will naturally flock to it.

**Comment by James4Ever0** [comment]
Keep posting these will not help. AGI is for everyone, truely democratic.

**Comment by James4Ever0** [comment]
For inspiration, please check #37

**Comment by michaelhhogue** [comment]
@alafortu Thanks for the suggestion. Low accuracy with GPT-4v is a known issue at the moment, and support for other models is planned in the future.
